// src/pages/TaskDetail.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { replace } from "svelte-spa-router";
  import { fly } from "svelte/transition";

  import { router, tasks, toaster } from "../stores";
  import { TaskModel, dateToString } from "../models/TaskModel";
  import WeekSelector from "../components/WeekSelector.svelte";

  export let params: { id: string };

  let task: TaskModel = new TaskModel();

  let last;
  let subscribe;
  let create = false;
  $: create = params.id === "new";

  onMount(() => {
    if (params.id === "new") {
      router.title.set("New task");
      router.canGoBack.set(true);
      last = dateToString(task.mostRecentExecution);
    } else {
      router.title.set("Edit task");
      subscribe = tasks.subscribe(_tasks => {
        task = _tasks.find(t => t.id === parseInt(params.id));
        if (!(task instanceof TaskModel)) {
          return replace("/");
        }
        last = dateToString(task.mostRecentExecution);
      });
    }
  });

  onDestroy(() => {
    if (subscribe instanceof Function) {
      subscribe();
    }
  });

  const saveTask = () => {
    if (!TaskModel.isValid(task) || !last) {
      return toaster.add({
        title: "All fields are required",
        duration: 3000
      });
    }

    if (dateToString(task.mostRecentExecution) !== last) {
      const date = new Date(last);
      const [mostRecent, ...rest] = task.executions;
      mostRecent.setFullYear(
        date.getFullYear(),
        date.getMonth(),
        date.getDate()
      );
    }

    tasks.save(task);
    replace("/");
  };

  const removeTask = () => {
    const deletedTask = task;

    toaster.add({
      title: `${task.title} has been removed`,
      action: {
        title: "Undo",
        callback: () => tasks.save(deletedTask)
      }
    });

    tasks.deleteById(task.id);
    replace("/");
  };
</script>

<style lang="scss">
  @import "../styles/colors";

  $margin: 30px;

  main {
    padding: $margin;
    height: calc(100% - #{2 * $margin});
    display: flex;
    flex-direction: column;
    justify-content: space-between;

    .title {
      // margin: 0;
      padding-bottom: $margin;
    }

    label {
      font-weight: bold;
      padding-bottom: 10px;

      & + * {
        margin-bottom: $margin;
      }
    }

    input {
      width: calc(100% - #{0 * $margin});

      &[type="date"] {
        display: block;
        -webkit-appearance: textfield;
        -moz-appearance: textfield;
        min-height: 2em;
        background-color: white;
      }
    }

    button {
      background-color: $blue;
      color: white;
      padding: 15px 40px;
      border-radius: 5px;
      width: calc(100% - 60px);
      margin: 0 30px;
    }

    .remove {
      color: $darkRed;
      font-weight: bold;
      display: flex;
      justify-content: center;
      padding-top: #{$margin / 2};
    }
  }
</style>

{#if task}
  <main in:fly={{ duration: 300, x: 280 }} out:fly={{ duration: 300, x: 280 }}>
    <div class="top">
      <label>Let's give it a name!</label>
      <input bind:value={task.title} />

      <label>When do you usually do this task?</label>
      <div class="week">
        <WeekSelector bind:value={task.when} />
      </div>

      <label>When did you last do this?</label>
      <input type="date" bind:value={last} />
    </div>
    <div class="bottom">

      <button on:click|preventDefault={saveTask}>
        {create ? 'Create' : 'Update'}
      </button>

      {#if !create}
        <div class="remove" on:click|preventDefault={removeTask}>
          Remove this task
        </div>
      {/if}
    </div>

  </main>
{/if}

// src/pages/TaskDetail.tsx
import React, { useState } from 'react';
import { useHistory } from "react-router-dom";
import { Task, getTask, deleteTask, saveTask } from '../data/tasks';
import {
  IonBackButton,
  IonButton,
  IonButtons,
  IonContent,
  IonDatetime,
  IonHeader,
  IonInput,
  IonItem,
  IonLabel,
  IonPage,
  IonTitle,
  IonToast,
  IonToolbar,
  useIonViewWillEnter
} from '@ionic/react';
import styled from 'styled-components';
import { RouteComponentProps } from 'react-router';
import WeekSelector from '../components/week/WeekSelector';

interface TaskDetailProps extends RouteComponentProps<{ id: string; }> { }

const AtoZCol = styled.div`
display: flex;
flex-direction: column;
justify-content: space-between;
height: 100%;

.actions {
  display: flex;
  flex-direction: column;
  padding: 0 30px 30px;

  .remove {
    padding-top: 15px;
    text-align: center;
    color: var(--ion-color-danger);
    font-weight: bold;
  }
}
`;

const TaskDetail: React.FC<TaskDetailProps> = ({ match }) => {

  const [task, setTask] = useState<Task>();
  const [title, setTitle] = useState<string>('');
  const [when, setWhen] = useState<number[]>([]);
  const [lastExecution, setLastExecution] = useState<Date>(new Date());
  const [isFormValid, setIsFormValid] = useState<boolean>(true);
  const history = useHistory();

  useIonViewWillEnter(() => {
    const t: Task | undefined = getTask(parseInt(match.params.id, 10));
    if (t) {
      console.log(t);
      setTask(t);
      setTitle(t.title);
      setWhen(t.when);
      const exec = [...t.executions].sort((a, b) => b.getTime() - a.getTime())
      setLastExecution(exec[0]);
    }
  });

  const changeLastExecution = (date: string) => {
    setLastExecution(new Date(date));
  }

  const save = () => {
    if (!title || !title.length || !when || !when.length || !lastExecution) {
      setIsFormValid(false);
      return;
    }
    let executions = task ? [...task.executions].sort((a, b) => b.getTime() - a.getTime()) : [];
    executions[0] = lastExecution;
    saveTask({ ...task, title, when, executions } as Task);
    history.push("/tasks");
  }

  const remove = (task: Task) => {
    deleteTask(task);
    history.push("/tasks");
  }

  return (
    <IonPage id="task-detail-page">
      <IonHeader translucent>
        <IonToolbar>
          <IonButtons>
            <IonBackButton text="Tasks" defaultHref="/tasks"></IonBackButton>
          </IonButtons>
          <IonTitle>{task ? 'Edit task' : 'New task'}</IonTitle>
        </IonToolbar>
      </IonHeader>

      <IonContent fullscreen>
        <AtoZCol>
          <div>
            <IonItem>
              <IonLabel position="stacked">Let's give it a name</IonLabel>
              <IonInput value={title} onIonChange={e => setTitle(e.detail.value!)} />
            </IonItem>
            <IonItem>
              <IonLabel position="stacked">When do you usually do this task?</IonLabel>
              <WeekSelector when={when} onValueChange={data => setWhen(data)} />
            </IonItem>
            <IonItem>
              <IonLabel position="stacked">When did you last do this?</IonLabel>
              <IonDatetime displayFormat="DDDD MMM D, YYYY"
                value={lastExecution?.toISOString()} onIonChange={e => changeLastExecution(e.detail.value!)}>
              </IonDatetime>
            </IonItem>
          </div>
          <div className="actions">
            <IonButton onClick={save} expand="block">{task ? 'Update' : 'Create'}</IonButton>
            {task && (<span className='remove' onClick={() => remove(task)}>Remove this task</span>)}
          </div>
        </AtoZCol>
        <IonToast
          isOpen={!isFormValid}
          onDidDismiss={() => setIsFormValid(true)}
          message="All fields are required."
          duration={1000}
        />
      </IonContent>
    </IonPage>
  );
};

export default TaskDetail;
